export enum SkippedReasons {
  SALE_END_DATE = 'SALE_END_DATE',
  TPR_END_DATE = 'TPR_END_DATE',
  INVENTORY_NP = 'INVENTORY_NP',
  LIKE_CODE_PROCESSED = 'LIKE_CODE_PROCESSED',
  PROVIDER_RESTRICTION = 'PROVIDER_RESTRICTION',
}
