export enum RoundingRules {
  BRAVO_SUPERMARKET = 'BRAVO_SUPERMARKET',
  KEYFOOD_HOLLYWOOD = 'KEYFOOD_HOLLYWOOD',
  BODEGON_3 = 'BODEGON_3',
  CARIBBEAN_SUPERCENTER = 'CARIBBEAN_SUPERCENTER',
  DEFAULT = 'DEFAULT',
}
